application:
  max-allowed-books: 15

server:
  port: 8180

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sem_5_28-05-2024_hw
    username: root
    password: 61208619
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      dll-auto: create-drop